SELECT *
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID);


SELECT * FROM EMPLOYEE ORDER BY JOB_CODE ASC;

SELECT * FROM JOB ORDER BY JOB_CODE DESC;



EMPLOYEE -> JOB -> DEPARTMENT 