SELECT *
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID);
JOIN JOB J ON (J.JOB_CODE = E.JOB_CODE);


SELECT * FROM EMPLOYEE ORDER BY JOB_CODE ASC;

SELECT * FROM JOB ORDER BY JOB_CODE DESC;



--EMPLOYEE -> JOB -> DEPARTMENT 
--저 순서대로 해야하는 이유?
--왜 JOB은 LEFT OR RIGHT JOIN을 안할까?

-- 1. 부서가 없는 직원이 있기때문에 DEPARTMENT -> JOB 순서로 JOIN하면 D.DEPT_CODE가 NULL인 직원의 JOB테이블 값은 된다
-- 2. JOB과 EMPLOYEE가 JOIN할때 J.JOB_CODE와 E.JOB_CODE를 사용하는데,
--    E.JOB_CODE에 NULL값없이 모두 JOB_CODE가 들어가있어서 데이터손실없이 JOIN이 가능하기 때문에