-- 게시글용 테이블 구현하기
-- 파일첨부 기능 구현할 것 + 댓글 기능 구현할 것

CREATE TABLE TB_SPRING_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER VARCHAR2(10) NOT NULL REFERENCES KH_MEMBER,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
	CHANGE_NAME VARCHAR2(200),
	STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N'))
);


DROP TABLE TB_SPRING_BOARD;

INSERT INTO TB_SPRING_BOARD(BOARD_TITLE, BOARD_WRITER)
 VALUES('첫번째 글', 'admin');

SELECT * FROM TB_SPRING_BOARD;


